ENT.Type = "anim"
ENT.PrintName = "Big Keg 'o Health"
ENT.Base = "ut2004_health_base"
ENT.Category = "Unreal Tournament 2004"
ENT.Author = "Hidden"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true