ENT.Type = "anim"
ENT.Base = "ut2004_armor_base"
ENT.PrintName = "Super Shield"
ENT.Category = "Unreal Tournament 2004"
ENT.Author = "Upset"
ENT.Contact = ""
ENT.Purpose = ""
ENT.Instructions = ""
ENT.Spawnable = true
ENT.AdminOnly = true